---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: update
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks: 

   - name: install apache and php
     tags: apache2, php
     package:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"

- hosts: file_server
  become: true
  tasks:

  - name: install mariadb and samba
    tags: mariadb, samba
    apt:
      name: 
        - mariadb-server
        - samba
      state: latest
